### ISSUE TITLE
Join Us page Design and Flow

### ISSUE THREAD

**Issue by eleanorgraham** [sartography/star-drive#148]
Update design to match new specs and verify that the initial sign-up process functions as desired

**Comment by calexh-sar** [comment]
Closing this ticket since primary work is on staging and Rose indicated that update photo can be updated post Oct. 1 launch in Slack on 09/11:

Alex Herron 11:44 AM
Good morning, @Rose Nevill Checking to see if any decision has been made yet regarding the photo for the Join Us page.
Rose Nevill 1:03 PM
@Alex Herron Not yet but we will send something as soon as possible.
Alex Herron 1:04 PM
Thanks for the update.
Rose Nevill 1:05 PM
I'm okay with making that a post-launch change if need be

Update Photo ticket: #209
