### ISSUE TITLE
Study Enrollment Scenario 2 Updates

### ISSUE THREAD

**Issue by calexh-sar** [sartography/star-drive#191]
From [slide 29 of the feedback deck](https://docs.google.com/presentation/d/1m49n2CCNruc80vFHFpLImbCrogKH0l9nIk0Zaj6f6J4/edit?pli=1#slide=id.g5e1cf4fb5a_0_245):

Current user clicks the **Sign In** button under the **Interested in Enrolling** section of a current study open for enrollment.  They are redirected to the Sign In page, enter their email address and password and click the **Submit** button

**Expected behavior:** Taken back to the current study so they can next click on the **Learn More** button.  The user is then 

**Current behavior:** Taken to the Profile page 

After clicking the **Learn More** button, if the user is potential participant, or if the user only has registered one dependent and the enrollment form is complete, display that participant information has been sent to researchers.  If enrollment form information is not complete, redirect to the enrollment forms page.  Upon successful completion of the enrollment information, redirect back to the current study so they can click on the **Learn More** button again to send completed participant information to researchers.

If more than one dependent has been added, prompt the user to select which participant they wish to be considered.  This step will need to be completed for each dependent to be considered.  If the dependent's enrollment information is not complete, send to enrollment forms page.  Upon successful completion of the enrollment information, redirect back to the current study so they can click on the **Learn More** button again and select the dependent to be considered.

**Comment by eleanorgraham** [comment]
This is a good example of one of the requirements that has shifted since the feedback deck was created. We talked with them about simplifying the flow so that there isn't the participant selection that is mentioned in the last paragraph here. In the meeting they approved us moving forward with this simplified version that simply ties the user and the study together. 

From what I can tell, the only remaining requirement on this ticket is changing the redirect behavior on sign in (back to the study). This fix is complete and will be in my upcoming pull request.

**Comment by calexh-sar** [comment]
Closing per Eleanor's comments above.
