### ISSUE TITLE
Assure agreement to Terms and Conditions

### ISSUE THREAD

**Issue by danfunk** [sartography/star-drive#2]
Assure all new accounts must view the terms and conditions document, and agree to those conditions before creating an account.

**Comment by eleanorgraham** [comment]
At the 12/18/18 meeting we discussed the flow of this, and talked about the possibility of putting the agreement to terms and conditions as part of the enrollment/registration process instead of account sign-up. There was concern that the terms would be very specific to study participants and be inappropriate for professional users. This flow needs to be thought through in tandem with getting a better understanding of user roles and permissions (related to issue #1 )

**Comment by eleanorgraham** [comment]
At the 4/23/19 meeting we agreed that Rose would provide the updated participant-type-specific terms once they've been approved, and we would move this agreement into the enrollment process.
